### ISSUE TITLE
Implementation request for Tikkie

### ISSUE THREAD

**Issue by IvoWams** [paynl/whmcs-plugin#3]
Add payment method Tikkie.

**Comment by jesgeerts** [comment]
Why would you need Tikkie as there is iDEAL?

**Comment by dzaal** [comment]
Tikkie is super important, lots of people use it nowadays and its perfect when doing collections. 
It need to be registerd on the invoice so our accountant can keep note where the money went.

**Comment by jesgeerts** [comment]
@dzaal You can use iDEAL or search for an web developer which it can generate an IDEAL url for the donation and creates automatically an invoice for your accountant. Depending on your accounting software it is possible to import such documents via email, FTP or API.
